variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - test
  - measure
  - documentation
  - deploy
  - secure

.config:
  image: lorisleiva/laravel-docker:8.2
  services:
    - mysql:latest
  before_script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:cache
    - chmod -R 775 storage bootstrap/cache
    - until mysqladmin ping -h "$DB_HOST" --silent; do sleep 5; done
    - php artisan migrate:refresh
    - php artisan db:seed

test:
  stage: test
  extends:
    - .config
  variables:
    APP_ENV: testing
    XDEBUG_MODE: coverage
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
  only:
    - master

measure:
  stage: measure
  extends:
    - .config
  script:
    - php vendor/bin/phpstan analyse --memory-limit=1G
    - php vendor/bin/phpinsights --no-interaction --ansi
  only:
    - master

documentation:
  stage: documentation
  extends:
    - .config
  script:
    - php vendor/bin/phpdoc run -d app/ -t docs/api
  only:
    - master

deploy:
  stage: deploy
  image: ubuntu
  only:
    - master
  script:
    - apt-get clean
    - apt-get -o Acquire::ForceIPv4=true update
    - apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d

secure:
  stage: secure
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs . --no-progress --format json -o trivy-report.json
  only:
    - master

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
