variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync

cache:
  paths:
    - vendor/
    - node_modules/
    - public/build/
    - storage/framework/cache/data/

stages:
  - build
  - test
  - measure
  - documentation
  - secure
  - deploy
  - publish

.config:
  image: lorisleiva/laravel-docker:8.2
  services:
    - mysql:latest
  before_script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:cache
    - chmod -R 775 storage bootstrap/cache
    - until mysqladmin ping -h"$DB_HOST" --silent; do sleep 5; done
    - php artisan migrate:refresh
    - php artisan db:seed

build:
  stage: build
  extends:
    - .config
  script:
    - npm run build
  only:
    - master

test:
  stage: test
  extends:
    - .config
  variables:
    APP_ENV: testing
    XDEBUG_MODE: coverage
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never --log-junit junit.xml
  artifacts:
    paths:
      - junit.xml
    reports:
      junit: junit.xml
    expire_in: 7 days
  only:
    - master

measure:
  stage: measure
  extends:
    - .config
  script:
    - php vendor/bin/phpinsights --no-interaction --ansi | tee insights-report.txt
  artifacts:
    paths:
      - insights-report.txt
    expire_in: 7 days
  only:
    - master

documentation:
  stage: documentation
  extends:
    - .config
  script:
    - php vendor/bin/phpdoc run -d app/ -t docs/api
  artifacts:
    paths:
      - docs
    expire_in: 7 days
  only:
    - master

secure:
  stage: secure
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs . --severity HIGH,CRITICAL --scanners vuln --skip-files "vendor/bin/phpdoc" --skip-files "vendor/laravel/pint/builds/pint" --format table -o trivy-report.table
  allow_failure: true
  artifacts:
    paths:
      - trivy-report.table
    expire_in: 7 days
  only:
    - master

deploy:
  stage: deploy
  image: ubuntu
  only:
    - master
  dependencies:
    - documentation
  script:
    - ls -la
    - apt-get clean
    - apt-get -o Acquire::ForceIPv4=true update
    - apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d

pages:
  stage: publish
  script:
    # Créer un fichier index.html de base
    - mkdir -p public

    # Créer l'entête HTML avec tee pour gérer correctement l'ordre d'écriture
    - echo "<html lang='en'>" | tee public/index.html
    - echo "<head>" | tee -a public/index.html
    - echo "<meta charset='UTF-8'>" | tee -a public/index.html
    - echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" | tee -a public/index.html
    - echo "<title>Consolidated Reports</title>" | tee -a public/index.html
    - echo "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css'>" | tee -a public/index.html
    - echo "</head>" | tee -a public/index.html
    - echo "<body>" | tee -a public/index.html
    - echo "<div class='container'>" | tee -a public/index.html
    - echo "<h1>Consolidated Reports</h1>" | tee -a public/index.html
    - echo "<table class='striped'>" | tee -a public/index.html
    - echo "<thead><tr><th>Report Type</th><th>Link</th></tr></thead><tbody>" | tee -a public/index.html

    # Parcourir les répertoires pour ajouter les liens dynamiques
    - for dir in public/*; do
        if [ -d "$dir" ]; then
          branch_pipeline=$(basename "$dir")
          echo "<tr><td>JUnit Report</td><td><a href='$branch_pipeline/junit_report.txt' target='_blank'>View</a></td></tr>" | tee -a public/index.html
          echo "<tr><td>PMD Report</td><td><a href='$branch_pipeline/result.xml' target='_blank'>View</a></td></tr>" | tee -a public/index.html
          echo "<tr><td>Javadoc</td><td><a href='$branch_pipeline/javadoc/index.html' target='_blank'>View</a></td></tr>" | tee -a public/index.html
        fi
      done

    # Clôturer le fichier HTML
    - echo "</tbody></table>" | tee -a public/index.html
    - echo "</div>" | tee -a public/index.html
    - echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js'></script>" | tee -a public/index.html
    - echo "</body>" | tee -a public/index.html
    - echo "</html>" | tee -a public/index.html

  artifacts:
    paths:
      - public/index.html
  only:
    - master

