variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync
cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - test
  - measure
  - deploy
  - secure

.config:
  image: lorisleiva/laravel-docker:8.2
  services:
    - mysql:latest
  before_script:
    # Install Node dependencies.
    - npm install
    # install composer dependencies
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    # Copy over example configuration.
    # Don't forget to set the database config in .env.example correctly
    - cp .env.example .env
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:cache
    - chmod -R 775 storage bootstrap/cache
    # Run database migrations.
    - php artisan migrate:refresh
    - php artisan db:seed

test:
  stage: test
  extends:
    - .config
  variables:
    APP_ENV: testing
    XDEBUG_MODE: coverage  # Enable only coverage mode
  script:
    # run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never
    # run frontend tests
    # if you have any task for testing frontend
    # set it in your package.json script
    # comment this out if you don't have a frontend test
    #- npm test
  only:
    - master

measure:
  stage: measure
  extends:
    - .config
  script:
    - php vendor/bin/phpstan analyse --memory-limit=1G
  only:
    - master

deploy:
  stage: deploy
  script:
    - curl -fsSL cli.railway.app | sh
    - railway up
  environment:
    name: production
  only:
    - master

secure:
  stage: secure
  image: aquasec/trivy:latest
  script:
    # Scan the Laravel project directory for vulnerabilities
    - trivy fs --exit-code 1 --no-progress --format json -o trivy-report.json .
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 hour
  only:
    - master
