variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync

cache:
  paths:
    - vendor/
    - node_modules/
    - public/build/
    - storage/framework/cache/data/

stages:
  - build
  - test
  - measure
  - documentation
  - secure
  - deploy
  - publish

.config:
  image: lorisleiva/laravel-docker:8.2
  services:
    - mysql:latest
  before_script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:cache
    - chmod -R 775 storage bootstrap/cache
    - until mysqladmin ping -h"$DB_HOST" --silent; do sleep 5; done
    - php artisan migrate:refresh
    - php artisan db:seed

build:
  stage: build
  extends:
    - .config
  script:
    - npm run build
  only:
    - master

test:
  stage: test
  extends:
    - .config
  variables:
    APP_ENV: testing
    XDEBUG_MODE: coverage
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never --log-junit junit.xml
  artifacts:
    paths:
      - junit.xml
    reports:
      junit: junit.xml
    expire_in: 7 days
  only:
    - master

measure:
  stage: measure
  extends:
    - .config
  script:
    - php vendor/bin/phpinsights --no-interaction --ansi | tee insights-report.txt
  artifacts:
    paths:
      - insights-report.txt
    expire_in: 7 days
  only:
    - master

documentation:
  stage: documentation
  extends:
    - .config
  script:
    - php vendor/bin/phpdoc run -d app/ -t docs/api
  artifacts:
    paths:
      - docs
    expire_in: 7 days
  only:
    - master

secure:
  stage: secure
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs . --severity HIGH,CRITICAL --scanners vuln --skip-files "vendor/bin/phpdoc" --skip-files "vendor/laravel/pint/builds/pint" --format table -o trivy-report.table
  allow_failure: true
  artifacts:
    paths:
      - trivy-report.table
    expire_in: 7 days
  only:
    - master

deploy:
  stage: deploy
  image: ubuntu
  only:
    - master
  script:
    - ls -la
    - apt-get clean
    - apt-get -o Acquire::ForceIPv4=true update
    - apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d

pages:
  stage: publish
  script:
    - echo "<html lang='en'>" > public/index.html
    - echo "<head>" >> public/index.html
    - echo "<meta charset='UTF-8'>" >> public/index.html
    - echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> public/index.html
    - echo "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css'>" >> public/index.html
    - echo "<title>Consolidated Reports</title>" >> public/index.html
    - echo "</head>" >> public/index.html
    - echo "<body>" >> public/index.html
    - echo "<div class='container'>" >> public/index.html
    - echo "<h1>Consolidated Reports</h1>" >> public/index.html
    - echo "<table class='striped'>" >> public/index.html
    - echo "<thead><tr><th>Report Type</th><th>Link</th></tr></thead><tbody>" >> public/index.html

    # Add JUnit Report link
    - if [ -f junit.xml ]; then
        cp junit.xml public/junit_report.xml;
        echo "<tr><td>JUnit Report</td><td><a href='junit_report.xml'>View JUnit Report</a></td></tr>" >> public/index.html;
      fi

    # Add PHP Insights Report link
    - if [ -f insights-report.txt ]; then
        cp insights-report.txt public/insights_report.txt;
        echo "<tr><td>PHP Insights Report</td><td><a href='insights_report.txt'>View PHP Insights Report</a></td></tr>" >> public/index.html;
      fi

    # Add API Documentation link
    - if [ -d docs/api ]; then
        cp -r docs/api public/api_docs;
        echo "<tr><td>API Documentation</td><td><a href='api_docs/index.html'>View API Documentation</a></td></tr>" >> public/index.html;
      fi

    # Add Trivy Security Report link
    - if [ -f trivy-report.table ]; then
        cp trivy-report.table public/trivy_report.txt;
        echo "<tr><td>Security Report (Trivy)</td><td><a href='trivy_report.txt'>View Security Report</a></td></tr>" >> public/index.html;
      fi

    - echo "</tbody></table>" >> public/index.html
    - echo "</div>" >> public/index.html
    - echo "<script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js'></script>" >> public/index.html
    - echo "</body>" >> public/index.html
    - echo "</html>" >> public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - master
