variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync

cache:
  paths:
    - vendor/
    - node_modules/
    - public/build/
    - storage/framework/cache/data/

stages:
  - build
  - test
  - measure
  - documentation
  - secure
  - deploy
  - publish

.config:
  image: lorisleiva/laravel-docker:8.2
  services:
    - mysql:latest
  before_script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:cache
    - chmod -R 775 storage bootstrap/cache
    - php artisan migrate:refresh
    - php artisan db:seed

build:
  stage: build
  extends:
    - .config
  script:
    - npm run build
  only:
    - master

test:
  stage: test
  extends:
    - .config
  variables:
    APP_ENV: testing
    XDEBUG_MODE: coverage
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never --log-junit phpunit.xml
  artifacts:
    paths:
      - phpunit.xml
    reports:
      junit: junit.xml
    expire_in: 7 days
  only:
    - master

measure:
  stage: measure
  extends:
    - .config
  script:
    - php vendor/bin/phpinsights analyse --no-interaction --ansi --format=json > insights-report.json
  artifacts:
    paths:
      - insights-report.json
    expire_in: 7 days
  only:
    - master

documentation:
  stage: documentation
  extends:
    - .config
  script:
    - php vendor/bin/phpdoc run -d app/ -t docs/api
  artifacts:
    paths:
      - docs
    expire_in: 7 days
  only:
    - master

secure:
  stage: secure
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs . --severity HIGH,CRITICAL --scanners vuln --skip-files "vendor/bin/phpdoc" --skip-files "vendor/laravel/pint/builds/pint" --format table -o trivy-report.table
  allow_failure: true
  artifacts:
    paths:
      - trivy-report.table
    expire_in: 7 days
  only:
    - master

deploy:
  stage: deploy
  image: ubuntu
  only:
    - master
  script:
    - ls -la
    - apt-get clean
    - apt-get -o Acquire::ForceIPv4=true update
    - apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d

pages:
  stage: publish
  script:
    # Create the public directory if it doesn't exist
    - mkdir -p public

    # Generate the index.html file with Tailwind CSS
    - echo "<!DOCTYPE html>" > public/index.html
    - echo "<html lang='en'>" >> public/index.html
    - echo "<head>" >> public/index.html
    - echo "<meta charset='UTF-8'>" >> public/index.html
    - echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> public/index.html
    - echo "<title>Consolidated Reports</title>" >> public/index.html
    - echo "<script src='https://cdn.tailwindcss.com'></script>" >> public/index.html
    - echo "</head>" >> public/index.html
    - echo "<body class='bg-gray-100 font-sans'>" >> public/index.html
    - echo "<div class='container mx-auto px-4 py-8'>" >> public/index.html
    - echo "<h1 class='text-3xl font-bold text-center text-gray-800 mb-8'>Pipeline Reports</h1>" >> public/index.html
    - echo "<div class='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6'>" >> public/index.html

    # Add JUnit Report link
    - if [ -f phpunit.xml ]; then
        - cp phpunit.xml public/phpunit_report.xml
        - echo "<div class='bg-white shadow-md rounded-lg p-6'>" >> public/index.html
        - echo "<h2 class='text-xl font-semibold text-gray-700'>PHPUnit Report</h2>" >> public/index.html
        - echo "<a href='phpunit_report.xml' class='text-blue-500 hover:text-blue-700'>View PHPUnit Report</a>" >> public/index.html
        - echo "</div>" >> public/index.html
    - fi

    # Add PHP Insights Report link
    - if [ -f insights-report.json ]; then
        - cp insights-report.json public/insights_report.json
        - echo "<div class='bg-white shadow-md rounded-lg p-6'>" >> public/index.html
        - echo "<h2 class='text-xl font-semibold text-gray-700'>PHP Insights Report</h2>" >> public/index.html
        - echo "<a href='insights_report.json' class='text-blue-500 hover:text-blue-700'>View PHP Insights Report</a>" >> public/index.html
        - echo "</div>" >> public/index.html
    - fi

    # Add API Documentation link
    - if [ -d docs/api ]; then
        - cp -r docs/api public/api_docs
        - echo "<div class='bg-white shadow-md rounded-lg p-6'>" >> public/index.html
        - echo "<h2 class='text-xl font-semibold text-gray-700'>Documentation</h2>" >> public/index.html
        - echo "<a href='api_docs/index.html' class='text-blue-500 hover:text-blue-700'>View Documentation</a>" >> public/index.html
        - echo "</div>" >> public/index.html
    - fi

    # Add Trivy Security Report link
    - if [ -f trivy-report.table ]; then
        - cp trivy-report.table public/trivy_report.txt
        - echo "<div class='bg-white shadow-md rounded-lg p-6'>" >> public/index.html
        - echo "<h2 class='text-xl font-semibold text-gray-700'>Security Report (Trivy)</h2>" >> public/index.html
        - echo "<a href='trivy_report.txt' class='text-blue-500 hover:text-blue-700'>View Security Report</a>" >> public/index.html
        - echo "</div>" >> public/index.html
    - fi

    - echo "</div>" >> public/index.html
    - echo "</div>" >> public/index.html
    - echo "</body>" >> public/index.html
    - echo "</html>" >> public/index.html

    - echo "url -> https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME/"
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - master
